name: Purge old images

on:
  schedule:
    - cron: '0 2 * * *'     # 07 :30 IST every day
  workflow_dispatch:

env:
  REGISTRY: swiftcheckacr

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1          # ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/CLI@v1
        with:
          inlineScript: |
            az acr run --registry $REGISTRY \
              --cmd "acr purge --filter 'swiftcheck-api:.*' --keep 2 --ago 0d" \
              /dev/null
