name: Trigger auto deployment for swiftcheck-api

on:
  push:
    branches: [ main ]
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SWIFTCHECKAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SWIFTCHECKAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SWIFTCHECKAPI_AZURE_SUBSCRIPTION_ID }}
      
      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile.azure
          containerAppName: swiftcheck-api
          resourceGroup: SwiftCheckAi
          registryUrl: swiftcheckacr.azurecr.io
          registryUsername: ${{ secrets.SWIFTCHECKAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SWIFTCHECKAPI_REGISTRY_PASSWORD }}